export enum ReportReason {
    SPAM = "SPAM",
    ADULT_CONTENT = "PORNOGRAPHY",
    CHILD_ABUSE = "CHILD_ABUSE",
    FRAUD = "FRAUD",
    MISLEADING_INFORMATION = "MISLEADING_INFORMATION",
    VIOLENCE = "VIOLENCE",
    HATE_SPEECH = "HATE_SPEECH",
    OTHER = "OTHER"
}
