export enum RegistrationStep {
    SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL",
    CHECK_VERIFICATION_CODE = "CHECK_VERIFICATION_CODE",
    CONFIRM_SKIPPING_EMAIL = "CONFIRM_SKIPPING_EMAIL",
    REGISTER = "REGISTER"
}
