export enum EmailConfirmationCodeType {
    CONFIRM_EMAIL = "CONFIRM_EMAIL",
    CONFIRM_PASSWORD_RESET = "CONFIRM_PASSWORD_RESET",
    CONFIRM_PASSWORD_RECOVERY = "CONFIRM_PASSWORD_RECOVERY",
    CONFIRM_EMAIL_CHANGE = "CONFIRM_EMAIL_CHANGE",
    UPDATE_EMAIL = "UPDATE_EMAIL",
    UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS",
    UPDATE_EMAIL_ERROR = "UPDATE_EMAIL_ERROR"
}
