export enum JoinChatRejectionReason {
    WRONG_USER_ID = "WRONG_USER_ID",
    INSUFFICIENT_VERIFICATION_LEVEL = "INSUFFICIENT_VERIFICATION_LEVEL",
    ALREADY_CHAT_PARTICIPANT = "ALREADY_CHAT_PARTICIPANT",
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
}
