export enum UploadType {
    IMAGE = "IMAGE",
    GIF = "GIF",
    VIDEO = "VIDEO",
    FILE = "FILE",
    AUDIO = "AUDIO",
    VOICE_MESSAGE = "VOICE_MESSAGE",
    IMAGE_STICKER = "IMAGE_STICKER",
    WEBP_STICKER = "WEBP_STICKER",
    LOTTIE_STICKER = "LOTTIE_STICKER",
    VIDEO_STICKER = "VIDEO_STICKER"
}
