version: "3.7"
services:
  gateway:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://localhost:8081/eureka/
    network_mode: host
