package chatox.chat.repository.elasticsearch

import chatox.chat.model.elasticsearch.ChatElasticsearch
import chatox.chat.repository.elasticsearch.custom.ChatCustomElasticsearchRepository
import org.springframework.data.repository.reactive.ReactiveCrudRepository

interface ChatElasticsearchRepository : ReactiveCrudRepository<ChatElasticsearch, String>, ChatCustomElasticsearchRepository