version: "3.7"
services:
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./oauth2-init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chatox-oauth2-service
    ports:
    - "5433:5432"
    restart: unless-stopped
  oauth2:
    build:
      context: .
    restart: always
    ports:
      - "8082:8082"
    environment:
      - EUREKA_URL=http://localhost:8081/eureka
      - POSTGRES_URL=jdbc:postgresql://localhost:5433/chatox-oauth2-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - postgres
    network_mode: host
volumes:
  pg-data: {}
