version: "3.7"
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=chatox_chat_service
    ports:
      - 27017
    restart: unless-stopped
  chat-service:
    build:
      context: .
    restart: always
    ports:
      - "8085:8085"
    environment:
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - EUREKA_URL=http://localhost:8081/eureka/
    depends_on:
      - mongo
    network_mode: host
