package chatox.chat.messaging.rabbitmq.event

enum class UploadDeletionReasonType {
    MESSAGE_UPDATED_EVENT,
    MESSAGE_DELETED_EVENT,
    CHAT_DELETED_EVENT,
    CHAT_UPDATED_EVENT,
    USER_PROFILE_PHOTO_DELETED_EVENT,
    USER_UPDATED_EVENT,
    STICKER_DELETED_EVENT,
    STICKER_PACK_UPDATED_EVENT,
    STICKER_PACK_DELETED_EVENT,
    DELETE_UPLOAD_REQUEST
}