export interface Labels {
    "error.unknown": string,
    "firstName": string,
    "firstName.empty": string,
    "firstName.too-long": string,
    "firstName.too-short": string,
    "lastName": string,
    "lastName.too-long": string
    "lastName.too-short": string,
    "login": string,
    "logout": string,
    "password": string,
    "password.do-not-match": string,
    "password.empty": string,
    "password.too-long": string,
    "password.too-short": string,
    "register": string,
    "registration.error.unknown": string
    "registration.success": string,
    "repeatedPassword": string,
    "server.unreachable": string
    "signIn": string,
    "singUp": string,
    "slug": string,
    "slug.contains-invalid-characters": string,
    "slug.has-already-been-taken": string,
    "slug.too-long": string,
    "slug.too-short": string,
    "username": string,
    "username.contains-invalid-characters": string,
    "username.empty": string,
    "username.has-already-been-taken": string
    "username.too-long": string,
    "username.too-short": string,
    "close": string,
    "cancel": string
}
