spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      filter:
        remove-non-proxy-headers:
          headers:
            - connection
            - keep-alive
            - transfer-encoding
            - te
            - trailer
            - proxy-authorization
            - proxy-authenticate
            - x-application-context
        remove-hop-by-hop:
          headers:
            - connection
            - keep-alive
            - transfer-encoding
            - te
            - trailer
            - proxy-authorization
            - proxy-authenticate
            - x-application-context
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
          '[/api/v1/events/**]':
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: oauth2
          uri: lb://oauth2-service
          predicates:
            - Path=/oauth/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chat/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/api/v1/registration/**
        - id: events-service
          uri: lb://events-service
          predicates:
            - Path=/api/v1/events/**
        - id: events-service-websocket
          uri: lb:ws://events-service
          predicates:
            - Path=/**
eureka:
  client:
    enabled: true
    service-url.defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: chatox-gateway
    instance-id: chatox-gateway-${server.port}
server:
  port: 8080
