spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/api/v1/notification/handshake/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: oauth2
          uri: lb://oauth2-service
          predicates:
            - Path=/oauth/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chat/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/api/v1/registration/**
        - id: notification-service
          uri: lb:ws//notification-service
          predicates:
            - Path=/api/v1/notification/**
eureka:
  client:
    enabled: true
    service-url.defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: chatox-gateway
    instance-id: chatox-gateway-${server.port}
server:
  port: 8080
