version: "3.7"
services:
  lottie:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${FLASK_LOTTIE_SERVICE_PORT}:${FLASK_LOTTIE_SERVICE_PORT}
    tty: true
    network_mode: host
