server:
  port: 8089
spring:
  application:
    name: wallet-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chatox-wallet-service}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      initialization-fail-timeout: 50000
      connection-timeout: 6000
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chatox-wallet-service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        merge:
          entity_copy_observer: allow
        cache:
          use_second_level_cache: true
    show-sql: false
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: 'wallet-service'
    instance-id: 'wallet-service-${server.port}'
ribbon:
  eureka:
    enabled: true

