spring:
  application:
    name: registration-service
  security:
    oauth2:
      client:
        provider:
          registration-service:
            token-uri: ${TOKEN_URL:http://localhost:8080/oauth2/token}
        registration:
          registration-service:
            client-id: ${REGISTRATION_SERVICE_CLIENT_ID:9e6f556f-0321-4b11-b6b0-ddb7da2ead16}
            client-secret: ${REGISTRATION_SERVICE_CLIENT_SECRET:secret}
            authorization-grant-type: client_credentials
            scope:
              - internal_create_user
              - internal_create_account
              - internal_update_account
server:
  port: 8084
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: 'registration-service'
    instance-id: 'registration-service-${server.port}'
ribbon:
  eureka:
    enabled: true
gateway:
  base:
    url: ${GATEWAY_URL:http://localhost:8080}
