export enum PasswordRecoveryStep {
    CREATE_EMAIL_CONFIRMATION_CODE = "CREATE_EMAIL_CONFIRMATION_CODE",
    CHECK_EMAIL_CONFIRMATION_CODE = "CHECK_EMAIL_CONFIRMATION_CODE",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    PASSWORD_RECOVERY_COMPLETED = "PASSWORD_RECOVERY_COMPLETED"
}
