export enum UploadDeletionReasonType {
    MESSAGE_UPDATED_EVENT = "MESSAGE_UPDATED_EVENT",
    MESSAGE_DELETED_EVENT = "MESSAGE_DELETED_EVENT",
    MESSAGES_DELETED_EVENT = "MESSAGES_DELETED_EVENT",
    CHAT_DELETED_EVENT = "CHAT_DELETED_EVENT",
    CHAT_UPDATED_EVENT = "CHAT_UPDATED_EVENT",
    USER_PROFILE_PHOTO_DELETED_EVENT = "USER_PROFILE_PHOTO_DELETED_EVENT",
    USER_UPDATED_EVENT = "USER_UPDATED_EVENT",
    USER_DELETED_EVENT = "USER_DELETED_EVENT",
    DELETE_UPLOAD_REQUEST = "DELETE_UPLOAD_REQUEST"
}