export enum UploadReferenceType {
    MESSAGE_ATTACHMENT = "MESSAGE_ATTACHMENT",
    CHAT_PROFILE_IMAGE = "CHAT_PROFILE_IMAGE",
    USER_PROFILE_IMAGE = "USER_PROFILE_IMAGE",
    STICKER = "STICKER"
}