server:
  port: 8082
spring:
  application:
    name: oauth2-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chatox-oauth2-service}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      initialization-fail-timeout: 50000
      connection-timeout: 6000
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chatox-oauth2-service}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root}
  main:
    allow-bean-definition-overriding: true
  mail:
    host: ${OAUTH2_SERVICE_SPRING_MAIL_HOST}
    username: ${OAUTH2_SERVICE_SPRING_MAIL_USERNAME}
    password: ${OAUTH2_SERVICE_SPRING_MAIL_PASSWORD}
    port: ${OAUTH2_SERVICE_SPRING_MAIL_PORT}
    default-encoding: UTF-8
    protocol: ${OAUTH2_SERVICE_SPRING_MAIL_PROTOCOL}
    full-email: ${OAUTH2_SERVICE_FULL_EMAIL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        merge:
          entity_copy_observer: allow
    show-sql: true
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: 'oauth2-service'
    instance-id: 'oauth2-service-${server.port}'
ribbon:
  eureka:
    enabled: true
