export enum EventType {
    MESSAGE_CREATED = "MESSAGE_CREATED",
    MESSAGE_UPDATED = "MESSAGE_UPDATED",
    MESSAGE_DELETED = "MESSAGE_DELETED",
    USER_JOINED_CHAT = "USER_JOINED_CHAT",
    USER_LEFT_CHAT = "USER_LEFT_CHAT",
    USER_KICKED_FROM_CHAT = "USER_KICKED_FROM_CHAT",
    USER_BLOCKED_IN_CHAT = "USER_BLOCKED_IN_CHAT",
    USER_UPDATED = "USER_UPDATED",
    USER_DELETED = "USER_DELETED"
}
